### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by doctor2018** [tranxuanthang/villain3ds#4] opened 2017-11-20 21:22 UTC
hi my friends, when i try to download any title i have this error message:

Something bad happened when working with downloaded tmd file (TypeError: Cannot read property 'length' of undefined).
Maybe i'm making something wrong? please your help.

**Comment by tranxuanthang** [comment] 2017-11-21 05:58
Something goes wrong when the app trying to create `cetk` file (the ticket file) from `tmd` file (the title metadata file). I think the downloaded tmd file is corrupted somehow.
Does this happen with every titles? Could you take one of the `tmd` file in a title's raw folder as example?

**Comment by OneEss** [comment] 2017-11-21 10:02
Removing the "Villain3DS" entirely from the user folder fixes the problem.

**Comment by tranxuanthang** [comment] 2017-11-21 11:08
@OneEss did you encounter this bug too? That's weird, I don't think there is any connection between `villain3ds` folder and that error.

**Comment by OneEss** [comment] 2017-11-21 13:57
@tranxuanthang I did, had a older version of the program that worked, in the newest version of the program I encounterd the same error, removing the tmd haven't had any effect, after I deleted the villain3ds folder itself and the program worked flawlessly.

**Comment by tranxuanthang** [comment] 2017-11-22 11:41
Thanks for your information. I'm gonna try to reinstall an older version and update it to see if I can reproduce the problem.

**Comment by tranxuanthang** [comment] 2017-12-02 18:05
Found the cause of this issue. It is because of an empty 0kb enctitlekeys.bin in your base folder. I'll research the problem further soon.

**Comment by tranxuanthang** [comment] 2018-01-17 12:11
Fixed in 0.1.2. If there is a 0byte enctitlekeys file or the titlekey for the title can't be found, it will now tell you to delete the enctitlekeys in 'base directory' and try again, instead of "undefined length" error.

**Closed as completed by tranxuanthang** 2018-01-17 12:11 UTC
